# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe4bca270048182942db4249569fa7e2247a4ae75e886770eafe3a6dacb4772a011f196ae4685717d908569faabd1114ce29cb17acfff76a79537e4616483be0

test:
  secret_key_base: a99cf61196e61c258afb8c8557b55154ef3a328a3efe7c26ad4d1b9c9f8265785f03c3740583d449fad434ff69ba98acda7111e67b5bc31f03043674e0accc81

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
